//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { IChartSeriesBag } from "@Obsidian/ViewModels/Blocks/Reporting/iChartSeriesBag";
import { ChartOptionsBag } from "@Obsidian/ViewModels/Reporting/chartOptionsBag";

/** Represents a bar chart, including its labels, bar series, and configuration. */
export type PieChartBag = {
    /** Gets or sets the chart options bag, which contains configuration options for the chart. */
    chartOptionsBag?: ChartOptionsBag | null;

    /** Gets or sets the labels for the data points. */
    labels?: string[] | null;

    /** Gets or sets one or more bar series data. */
    seriesBags?: IChartSeriesBag[] | null;
};
